version: "3"

services:

    router:
        image: "nginx:latest"
        volumes:
            - "./routes.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"

    backend_prod_01:
        image: "nginx:latest"
        working_dir: /usr/share/nginx/html

    backend_dev_01:
        image: "nginx:latest"
        working_dir: /usr/share/nginx/html
        volumes:
            - "./routes.conf:/usr/share/nginx/html/index.html"
